
echo off
echo Clean utility
echo This script removes all autogenerated files
echo Use it to reduce the number of files for SLab realse

%SystemRoot%\System32\choice.exe /C YN /N /M "Are you sure [Y/N]? "
if errorlevel 2 goto :nothing

echo Start cleaning...
cd ..

echo F303RE Source
del Boards\F303RE\Firmware\Source\build\lst\*.lst
del Boards\F303RE\Firmware\Source\build\obj\*.o

echo Python pyc
del /S Code\*.pyc
del Console\*.pyc
rmdir /S /Q Code\__pycache__
rmdir /S /Q Code\slab\__pycache__

echo Code examples and tests
rmdir /S /Q Code\Examples
rmdir /S /Q Code\Tests 

echo Calibrations
del /S Code\Calibrations\*.dat 
rmdir /S /Q Code\Calibrations\*.*
del /Q Jupyter\Files\Calibrations\*.*
rmdir /S /Q Jupyter\Files\Calibrations\*.*

echo Checkpoints
rmdir /S /Q Jupyter\.ipynb_checkpoints
rmdir /S /Q Jupyter\Basics\.ipynb_checkpoints
rmdir /S /Q Jupyter\BJT\.ipynb_checkpoints
rmdir /S /Q Jupyter\Boards\Nucleo_F303RE_Zero\.ipynb_checkpoints
rmdir /S /Q Jupyter\Demo\.ipynb_checkpoints
rmdir /S /Q Jupyter\Diode\.ipynb_checkpoints
rmdir /S /Q "Jupyter\Linear AC\.ipynb_checkpoints"
rmdir /S /Q "Jupyter\Linear DC\.ipynb_checkpoints"
rmdir /S /Q "Jupyter\Linear Opamp\.ipynb_checkpoints"
rmdir /S /Q Jupyter\Reference\.ipynb_checkpoints
rmdir /S /Q Jupyter\Sandbox\.ipynb_checkpoints
rmdir /S /Q "Jupyter\SLab Kit\.ipynb_checkpoints"
rmdir /S /Q Jupyter\Tests\.ipynb_checkpoints
rmdir /S /Q Jupyter\User\*.*

echo Private 
rmdir /S/Q Jupyter\Private
rmdir /S/Q "Jupyter\Private SLab"

echo Files
del /Q Jupyter\Files\*.*

echo Done

goto :EOF

:nothing
echo Cleaning aborted